[env:cardkb_emulator]
platform    = https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
board       = rpipico
framework   = arduino

lib_deps =
    https://github.com/adafruit/Adafruit_TinyUSB_Arduino
    https://github.com/sekigon-gonnoc/Pico-PIO-USB

build_flags =
    -DUSE_TINYUSB
    -DCFG_TUH_ENABLED=1
    -DPIO_USB_DP_PIN_DEFAULT=0
    -DCFG_TUH_HID=4

monitor_speed = 115200
